### ISSUE TITLE
how can I use GPU?

### ISSUE THREAD

**Issue by yuzhaoke** [Replicable-MARL/MARLlib#137]
When I use the following code, I see that the GPU is not working(The rest of the code is consistent with Quick Start).

mappo.fit(env, model, local_mode=True, num_gpus=1)

When I change the local_mode to False, it will report an error：

(pid=1732990) 2023-06-30 15:37:56,149   ERROR worker.py:425 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::MAPPOTrainer.__init__() (pid=1732990, ip=172.17.0.3)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 137, in __init__
(pid=1732990)     Trainer.__init__(self, config, env, logger_creator)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 623, in __init__
(pid=1732990)     super().__init__(config, logger_creator)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 107, in __init__
(pid=1732990)     self.setup(copy.deepcopy(self.config))
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 147, in setup
(pid=1732990)     super().setup(config)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 776, in setup
(pid=1732990)     self._init(self.config, self.env_creator)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 171, in _init
(pid=1732990)     self.workers = self._make_workers(
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 858, in _make_workers
(pid=1732990)     return WorkerSet(
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 110, in __init__
(pid=1732990)     self._local_worker = self._make_worker(
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 406, in _make_worker
(pid=1732990)     worker = cls(
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 584, in __init__
(pid=1732990)     self._build_policy_map(
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1384, in _build_policy_map
(pid=1732990)     self.policy_map.create_policy(name, orig_cls, obs_space, act_space,
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/policy/policy_map.py", line 143, in create_policy
(pid=1732990)     self[policy_id] = class_(observation_space, action_space,
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/policy/policy_template.py", line 280, in __init__
(pid=1732990)     self._initialize_loss_from_dummy_batch(
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/policy/policy.py", line 731, in _initialize_loss_from_dummy_batch
(pid=1732990)     self.compute_actions_from_input_dict(
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 302, in compute_actions_from_input_dict
(pid=1732990)     return self._compute_action_helper(input_dict, state_batches,
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/utils/threading.py", line 21, in wrapper
(pid=1732990)     return func(self, *a, **k)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 366, in _compute_action_helper
(pid=1732990)     dist_inputs, state_out = self.model(input_dict, state_batches,
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/modelv2.py", line 243, in __call__
(pid=1732990)     res = self.forward(restored, state or [], seq_lens)
(pid=1732990)   File "/home/docker/MARLlib/marllib/marl/models/zoo/mlp/base_mlp.py", line 100, in forward
(pid=1732990)     self._features = self.p_encoder(self.inputs)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
(pid=1732990)     return forward_call(*input, **kwargs)
(pid=1732990)   File "/home/docker/MARLlib/marllib/marl/models/zoo/encoder/base_encoder.py", line 107, in forward
(pid=1732990)     output = self.encoder(inputs)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
(pid=1732990)     return forward_call(*input, **kwargs)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
(pid=1732990)     input = module(input)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
(pid=1732990)     return forward_call(*input, **kwargs)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/torch/misc.py", line 160, in forward
(pid=1732990)     return self._model(x)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
(pid=1732990)     return forward_call(*input, **kwargs)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
(pid=1732990)     input = module(input)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
(pid=1732990)     return forward_call(*input, **kwargs)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 96, in forward
(pid=1732990)     return F.linear(input, self.weight, self.bias)
(pid=1732990)   File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/torch/nn/functional.py", line 1847, in linear
(pid=1732990)     return torch._C._nn.linear(input, weight, bias)
(pid=1732990) RuntimeError: CUDA error: no kernel image is available for execution on the device
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    mappo.fit(env, model, local_mode=False, num_gpus=1)
  File "/home/docker/MARLlib/marllib/marl/__init__.py", line 315, in fit
    run_cc(self.config_dict, env_instance, model_class, stop=stop)
  File "/home/docker/MARLlib/marllib/marl/algos/run_cc.py", line 192, in run_cc
    results = POlICY_REGISTRY[exp_info["algorithm"]](model, exp_info, run_config, env_info, stop_config,
  File "/home/docker/MARLlib/marllib/marl/algos/scripts/mappo.py", line 110, in run_mappo
    results = tune.run(MAPPOTrainer,
  File "/home/docker/.conda/envs/marllib/lib/python3.8/site-packages/ray/tune/tune.py", line 624, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [MAPPOTrainer_mpe_simple_reference_01d5a_00000])

**Comment by fortyMiles** [comment]
hello, this looks like some environment configuration or resource allocation issue. Please make sure your resource is enough to run this program.

**Comment by yuzhaoke** [comment]
I have 112 cpu cores and 3 GPU(3090), I don't think it's a problem of lack of resources.
Can you give me a detailed environment configuration (I seem to have only found a description of the python environment in the guide).
And my code is:

from marllib import marl

# prepare env
env = marl.make_env(environment_name="mpe", map_name="simple_reference", force_coop=True)

# initialize algorithm with appointed hyper-parameters
mappo = marl.algos.mappo(hyperparam_source='mpe')

# build agent model based on env + algorithms + user preference
model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})

# start training
mappo.fit(env, model, stop={'timesteps_total': 1000000}, share_policy='group', local_mode=False, num_gpus=1)

**Comment by libin-star** [comment]
has this problem solved? @yuzhaoke
